[package]
name = "falconasm"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "", features = ["all-widgets"] }
crossterm = ""
rfd = ""
arboard = ""
thiserror = ""
comfy-table = ""

[profile.release]
opt-level = 3        # máxima optmizing
lto = "fat"          # complete LTO  
codegen-units = 1    # better perform
panic = "abort"      # less overhead
debug = false
incremental = false
