//! Turning an ELF image into an editable assembly listing.
//!
//! The 489-line RV32 disassembler that used to sit here was a verbatim copy of
//! the engine's own (`falcon::decoder::disasm`), format strings and all. It is
//! gone; `disasm_word` now delegates, so there is one disassembler to keep
//! right instead of two that could drift.

use crate::falcon;
use crate::falcon::pipeline::sim::reg_name;
use crate::falcon::program::elf::ElfSection;
use std::collections::HashMap;
use std::fmt::Write as _;

/// One RV32 word as assembly text.
///
/// Prefer `App::disassemble_at`, which asks the *active* backend. This stays
/// for the RV32-only paths — instruction-field editing and the ELF listing
/// below — that already hold a raw word rather than an address.
pub fn disasm_word(w: u32) -> String {
    falcon::decoder::disasm(w)
}

pub fn elf_to_asm_source(
    text_words: &[u32],
    text_base: u32,
    symbols: &HashMap<u32, Vec<String>>,
    sections: &[ElfSection],
) -> String {
    use falcon::instruction::Instruction::*;

    let n = text_words.len();
    let text_end = text_base.wrapping_add((n as u32) * 4);

    // ── Pass 1: find branch/jal targets that need synthetic labels ──────
    let mut need_label: std::collections::HashSet<u32> = std::collections::HashSet::new();
    for (i, &word) in text_words.iter().enumerate() {
        let pc = text_base.wrapping_add((i as u32) * 4);
        if let Ok(ins) = falcon::decoder::decode(word) {
            let target_imm: Option<i32> = match ins {
                Beq { imm, .. }
                | Bne { imm, .. }
                | Blt { imm, .. }
                | Bge { imm, .. }
                | Bltu { imm, .. }
                | Bgeu { imm, .. }
                | Jal { imm, .. } => Some(imm),
                _ => None,
            };
            if let Some(imm) = target_imm {
                let t = pc.wrapping_add(imm as u32);
                if t >= text_base && t < text_end && !symbols.contains_key(&t) {
                    need_label.insert(t);
                }
            }
        }
    }

    // ── Build combined label map: addr → first name to use in source ────
    let mut label_at: HashMap<u32, String> = HashMap::new();
    for (&addr, names) in symbols {
        if let Some(name) = names.first() {
            label_at.insert(addr, name.clone());
        }
    }
    for &addr in &need_label {
        label_at
            .entry(addr)
            .or_insert_with(|| format!("_L_{addr:08x}"));
    }

    // ── Pass 2: emit assembly text ───────────────────────────────────────
    let mut out = String::with_capacity(n * 40);
    let _ = writeln!(out, "# ELF disassembly — auto-generated by Raven");
    let _ = writeln!(out, "# text base: 0x{text_base:08x}  ({n} instructions)");
    let _ = writeln!(out);

    for (i, &word) in text_words.iter().enumerate() {
        let pc = text_base.wrapping_add((i as u32) * 4);

        // Blank line + label(s) before each labeled instruction
        if symbols.contains_key(&pc) || need_label.contains(&pc) {
            if i > 0 {
                let _ = writeln!(out);
            }
            if let Some(names) = symbols.get(&pc) {
                for name in names {
                    let _ = writeln!(out, "{name}:");
                }
            } else if let Some(name) = label_at.get(&pc) {
                let _ = writeln!(out, "{name}:");
            }
        }

        let line = disasm_with_labels(word, pc, &label_at);
        let _ = writeln!(out, "    {line}");
    }

    // ── Data sections ────────────────────────────────────────────────────
    // Group sections: .bss-like (no file bytes) need ".bss" context;
    // others need ".data" context.  Track which section we're currently in.
    let mut cur_section: Option<&str> = None;
    for sec in sections {
        let is_bss = sec.bytes.is_empty();
        let needed = if is_bss { ".bss" } else { ".data" };
        if cur_section != Some(needed) {
            let _ = writeln!(out);
            let _ = writeln!(out, "{needed}");
            cur_section = Some(needed);
        }
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "# --- {} (0x{:08x}, {} bytes) ---",
            sec.name, sec.addr, sec.size
        );
        if is_bss {
            // Symbol labels at the bss base, then .skip for size
            if let Some(names) = symbols.get(&sec.addr) {
                for name in names {
                    let _ = writeln!(out, "{name}:");
                }
            }
            let _ = writeln!(out, "    .skip {}", sec.size);
        } else {
            emit_data_words(&mut out, &sec.bytes, sec.addr, symbols);
        }
    }

    out
}

/// Disassemble one word, replacing branch/jal targets with label names.
fn disasm_with_labels(word: u32, pc: u32, labels: &HashMap<u32, String>) -> String {
    use falcon::instruction::Instruction::*;

    let lbl = |imm: i32| -> String {
        let target = pc.wrapping_add(imm as u32);
        labels
            .get(&target)
            .cloned()
            .unwrap_or_else(|| imm.to_string())
    };

    match falcon::decoder::decode(word) {
        Ok(ins) => match ins {
            Beq { rs1, rs2, imm } => {
                format!("beq  {}, {}, {}", reg_name(rs1), reg_name(rs2), lbl(imm))
            }
            Bne { rs1, rs2, imm } => {
                format!("bne  {}, {}, {}", reg_name(rs1), reg_name(rs2), lbl(imm))
            }
            Blt { rs1, rs2, imm } => {
                format!("blt  {}, {}, {}", reg_name(rs1), reg_name(rs2), lbl(imm))
            }
            Bge { rs1, rs2, imm } => {
                format!("bge  {}, {}, {}", reg_name(rs1), reg_name(rs2), lbl(imm))
            }
            Bltu { rs1, rs2, imm } => {
                format!("bltu {}, {}, {}", reg_name(rs1), reg_name(rs2), lbl(imm))
            }
            Bgeu { rs1, rs2, imm } => {
                format!("bgeu {}, {}, {}", reg_name(rs1), reg_name(rs2), lbl(imm))
            }
            Jal { rd, imm } => format!("jal  {}, {}", reg_name(rd), lbl(imm)),
            _ => disasm_word(word),
        },
        Err(_) => format!(".word 0x{word:08x}"),
    }
}

/// Emit data section bytes as `.word` / `.byte` directives, inserting symbol
/// labels at the appropriate addresses.
fn emit_data_words(out: &mut String, bytes: &[u8], base: u32, symbols: &HashMap<u32, Vec<String>>) {
    let mut i = 0usize;
    while i < bytes.len() {
        let addr = base.wrapping_add(i as u32);
        // Symbol label(s) at this address
        if let Some(names) = symbols.get(&addr) {
            for name in names {
                let _ = writeln!(out, "{name}:");
            }
        }
        // Emit 4 bytes as .word when 4-byte aligned and enough remain
        if i + 4 <= bytes.len() && addr % 4 == 0 {
            let w = u32::from_le_bytes(bytes[i..i + 4].try_into().unwrap());
            let _ = writeln!(out, "    .word 0x{w:08x}");
            i += 4;
        } else {
            let _ = writeln!(out, "    .byte 0x{:02x}", bytes[i]);
            i += 1;
        }
    }
}
