//! RV32's instruction reference.
//!
//! The rows lived in the TUI, which meant the reference pane showed RISC-V
//! whatever backend was loaded. They belong to the ISA, so they live with it
//! and reach a host through [`Assembler::documented_instructions`].

use crate::InstructionDoc;

const fn doc(
    kind: &'static str,
    mnemonic: &'static str,
    operands: &'static str,
    summary: &'static str,
) -> InstructionDoc {
    InstructionDoc::new(kind, mnemonic, operands, summary)
}

const fn expands(
    kind: &'static str,
    mnemonic: &'static str,
    operands: &'static str,
    summary: &'static str,
    expands_to: &'static str,
) -> InstructionDoc {
    InstructionDoc::expanding(kind, mnemonic, operands, summary, expands_to)
}

/// `R`/`I`/`U` name the RISC-V encoding formats; `M`, `F` and `Atomic` the
/// extensions; `Pseudo` an assembler expansion and `Dir` an assembler
/// directive rather than an instruction.
#[rustfmt::skip]
pub(super) const INSTRUCTIONS: &[InstructionDoc] = &[
    doc("R", "add", "rd, rs1, rs2", "rd = rs1 + rs2"),
    doc("R", "sub", "rd, rs1, rs2", "rd = rs1 - rs2"),
    doc("R", "and", "rd, rs1, rs2", "rd = rs1 & rs2"),
    doc("R", "or", "rd, rs1, rs2", "rd = rs1 | rs2"),
    doc("R", "xor", "rd, rs1, rs2", "rd = rs1 ^ rs2"),
    doc("R", "sll", "rd, rs1, rs2", "rd = rs1 << (rs2 & 31)"),
    doc("R", "srl", "rd, rs1, rs2", "rd = logical rs1 >> (rs2 & 31)"),
    doc("R", "sra", "rd, rs1, rs2", "rd = arithmetic rs1 >> (rs2 & 31)"),
    doc("R", "slt", "rd, rs1, rs2", "rd = 1 if rs1 < rs2 (signed) else 0"),
    doc("R", "sltu", "rd, rs1, rs2", "rd = 1 if rs1 < rs2 (unsigned) else 0"),
    doc("M", "mul", "rd, rs1, rs2", "rd = (rs1 * rs2) low 32 bits"),
    doc("M", "mulh", "rd, rs1, rs2", "rd = (rs1 * rs2) high 32 bits signed"),
    doc("M", "mulhsu", "rd, rs1, rs2", "rd = (signed rs1 * unsigned rs2) high 32 bits"),
    doc("M", "mulhu", "rd, rs1, rs2", "rd = (rs1 * rs2) high 32 bits unsigned"),
    doc("M", "div", "rd, rs1, rs2", "rd = rs1 / rs2 (signed integer division)"),
    doc("M", "divu", "rd, rs1, rs2", "rd = rs1 / rs2 (unsigned)"),
    doc("M", "rem", "rd, rs1, rs2", "rd = rs1 % rs2 (signed remainder)"),
    doc("M", "remu", "rd, rs1, rs2", "rd = rs1 % rs2 (unsigned)"),
    doc("I", "addi", "rd, rs1, imm", "rd = rs1 + imm (12-bit signed)"),
    doc("I", "xori", "rd, rs1, imm", "rd = rs1 ^ imm"),
    doc("I", "ori", "rd, rs1, imm", "rd = rs1 | imm"),
    doc("I", "andi", "rd, rs1, imm", "rd = rs1 & imm"),
    doc("I", "slti", "rd, rs1, imm", "rd = 1 if rs1 < imm (signed) else 0"),
    doc("I", "sltiu", "rd, rs1, imm", "rd = 1 if rs1 < imm (unsigned) else 0"),
    doc("I", "slli", "rd, rs1, shamt", "rd = rs1 << shamt (shamt 0..31)"),
    doc("I", "srli", "rd, rs1, shamt", "rd = logical rs1 >> shamt"),
    doc("I", "srai", "rd, rs1, shamt", "rd = arithmetic rs1 >> shamt"),
    doc("Load", "lb", "rd, imm(rs1)", "Load 1 byte signed from mem[rs1+imm]"),
    doc("Load", "lh", "rd, imm(rs1)", "Load 2 bytes signed from mem[rs1+imm]"),
    doc("Load", "lw", "rd, imm(rs1)", "Load 4 bytes from mem[rs1+imm]"),
    doc("Load", "lbu", "rd, imm(rs1)", "Load 1 byte unsigned from mem[rs1+imm]"),
    doc("Load", "lhu", "rd, imm(rs1)", "Load 2 bytes unsigned from mem[rs1+imm]"),
    doc("Store", "sb", "rs2, imm(rs1)", "Store low 1 byte of rs2 to mem[rs1+imm]"),
    doc("Store", "sh", "rs2, imm(rs1)", "Store low 2 bytes of rs2 to mem[rs1+imm]"),
    doc("Store", "sw", "rs2, imm(rs1)", "Store 4 bytes of rs2 to mem[rs1+imm]"),
    doc("Branch", "beq", "rs1, rs2, label", "Branch if rs1 == rs2"),
    doc("Branch", "bne", "rs1, rs2, label", "Branch if rs1 != rs2"),
    doc("Branch", "blt", "rs1, rs2, label", "Branch if rs1 < rs2 (signed)"),
    doc("Branch", "bge", "rs1, rs2, label", "Branch if rs1 >= rs2 (signed)"),
    doc("Branch", "bltu", "rs1, rs2, label", "Branch if rs1 < rs2 (unsigned)"),
    doc("Branch", "bgeu", "rs1, rs2, label", "Branch if rs1 >= rs2 (unsigned)"),
    doc("U", "lui", "rd, imm20", "rd = imm20 << 12 (loads upper 20 bits)"),
    doc("U", "auipc", "rd, imm20", "rd = PC + (imm20 << 12)"),
    doc("Jump", "jal", "label | rd, label", "Jump and link; rd defaults to ra"),
    doc("Jump", "jalr", "rd, rs1, imm", "Jump to rs1+imm & ~1; rd = return addr"),
    doc("SYS", "ecall", "", "System call — a7 selects service, a0 = arg/result"),
    doc("SYS", "ebreak", "", "Pause execution (debug breakpoint; resumable)"),
    doc("SYS", "halt", "", "End-of-hart stop; distinct from ebreak and not resumable"),
    doc("SYS", "fence", "", "Memory barrier across memory and device accesses"),
    doc("SYS", "fence.i", "", "Instruction-stream synchronization barrier"),
    doc("Atomic", "lr.w", "rd, (rs1)", "Load-reserved word from mem[rs1] into rd"),
    doc("Atomic", "sc.w", "rd, rs2, (rs1)", "Store-conditional rs2 to mem[rs1]; rd=0 success, 1 failure"),
    doc("Atomic", "amoswap.w", "rd, rs2, (rs1)", "Atomically swap mem[rs1] with rs2; rd gets old value"),
    doc("Atomic", "amoadd.w", "rd, rs2, (rs1)", "Atomically add rs2 to mem[rs1]; rd gets old value"),
    doc("Atomic", "amoxor.w", "rd, rs2, (rs1)", "Atomically XOR rs2 with mem[rs1]; rd gets old value"),
    doc("Atomic", "amoand.w", "rd, rs2, (rs1)", "Atomically AND rs2 with mem[rs1]; rd gets old value"),
    doc("Atomic", "amoor.w", "rd, rs2, (rs1)", "Atomically OR rs2 with mem[rs1]; rd gets old value"),
    doc("Atomic", "amomax.w", "rd, rs2, (rs1)", "Atomically signed-max mem[rs1] with rs2; rd gets old value"),
    doc("Atomic", "amomin.w", "rd, rs2, (rs1)", "Atomically signed-min mem[rs1] with rs2; rd gets old value"),
    doc("Atomic", "amomaxu.w", "rd, rs2, (rs1)", "Atomically unsigned-max mem[rs1] with rs2; rd gets old value"),
    doc("Atomic", "amominu.w", "rd, rs2, (rs1)", "Atomically unsigned-min mem[rs1] with rs2; rd gets old value"),
    expands("Pseudo", "nop", "", "No operation", "addi x0, x0, 0"),
    expands("Pseudo", "mv", "rd, rs", "rd = rs", "addi rd, rs, 0"),
    expands("Pseudo", "li", "rd, imm12", "Load 12-bit immediate into rd", "addi rd, x0, imm"),
    expands("Pseudo", "subi", "rd, rs1, imm", "rd = rs1 - imm", "addi rd, rs1, -imm"),
    expands("Pseudo", "neg", "rd, rs", "rd = -rs", "sub rd, x0, rs"),
    expands("Pseudo", "not", "rd, rs", "rd = ~rs (bitwise NOT)", "xori rd, rs, -1"),
    expands("Pseudo", "seqz", "rd, rs", "rd = 1 if rs == 0 else 0", "sltiu rd, rs, 1"),
    expands("Pseudo", "snez", "rd, rs", "rd = 1 if rs != 0 else 0", "sltu rd, x0, rs"),
    expands("Pseudo", "sltz", "rd, rs", "rd = 1 if rs < 0 else 0", "slt rd, rs, x0"),
    expands("Pseudo", "sgtz", "rd, rs", "rd = 1 if rs > 0 else 0", "slt rd, x0, rs"),
    expands("Pseudo", "la", "rd, label", "Load address of label into rd", "lui rd, hi; addi rd, rd, lo"),
    expands("Pseudo", "j", "label", "Unconditional jump to label", "jal x0, label"),
    expands("Pseudo", "call", "label", "Call subroutine at label", "jal ra, label"),
    expands("Pseudo", "jr", "rs", "Jump register (indirect)", "jalr x0, rs, 0"),
    expands("Pseudo", "ret", "", "Return from subroutine", "jalr x0, ra, 0"),
    expands("Pseudo", "push", "rs", "sp -= 4; store rs at 0(sp)", "addi sp,sp,-4; sw rs,0(sp)"),
    expands("Pseudo", "pop", "rd", "load rd from 0(sp); sp += 4", "lw rd,0(sp); addi sp,sp,4"),
    expands("Pseudo", "bez/beqz", "rs, label", "Branch if rs == 0", "beq rs, x0, label"),
    expands("Pseudo", "bnez", "rs, label", "Branch if rs != 0", "bne rs, x0, label"),
    expands("Pseudo", "bltz", "rs, label", "Branch if rs < 0", "blt rs, x0, label"),
    expands("Pseudo", "bgez", "rs, label", "Branch if rs >= 0", "bge rs, x0, label"),
    expands("Pseudo", "blez", "rs, label", "Branch if rs <= 0", "bge x0, rs, label"),
    expands("Pseudo", "bgtz", "rs, label", "Branch if rs > 0", "blt x0, rs, label"),
    expands("Pseudo", "bgt", "rs1, rs2, label", "Branch if rs1 > rs2 (signed)", "blt rs2, rs1, label"),
    expands("Pseudo", "ble", "rs1, rs2, label", "Branch if rs1 <= rs2 (signed)", "bge rs2, rs1, label"),
    expands("Pseudo", "bgtu", "rs1, rs2, label", "Branch if rs1 > rs2 (unsigned)", "bltu rs2, rs1, label"),
    expands("Pseudo", "bleu", "rs1, rs2, label", "Branch if rs1 <= rs2 (unsigned)", "bgeu rs2, rs1, label"),
    expands("Pseudo", "print", "rd", "Print integer in rd (a7=1000)", "addi a7,x0,1000; mv a0,rd; ecall"),
    expands("Pseudo", "print_str", "label", "Print NUL string at label", "strlen loop; write(a0=1,a1=buf,a2=len) [syscall 64]"),
    expands("Pseudo", "print_str_ln", "label", "Print NUL string + newline", "strlen loop; write buf; write '\\n' via stack [syscall 64]"),
    expands("Pseudo", "read", "label", "Read up to 256 bytes from stdin", "read(a0=0,a1=buf,a2=256) [syscall 63]"),
    expands("Pseudo", "read_byte", "label", "Read decimal → store 1 byte (RAVEN)", "addi a7,x0,1010; la a0,label; ecall"),
    expands("Pseudo", "read_half", "label", "Read decimal → store 2 bytes (RAVEN)", "addi a7,x0,1011; la a0,label; ecall"),
    expands("Pseudo", "read_word", "label", "Read decimal → store 4 bytes (RAVEN)", "addi a7,x0,1012; la a0,label; ecall"),
    expands("Pseudo", "random", "rd", "rd = random 32-bit word (getrandom)", "getrandom syscall via stack (4 bytes)"),
    expands("Pseudo", "random_bytes", "label, n", "Fill n random bytes at label", "getrandom(label, n, 0) syscall"),
    doc("F", "flw", "frd, imm(rs1)", "Load f32 from mem[rs1+imm] into frd"),
    doc("F", "fsw", "frs2, imm(rs1)", "Store f32 in frs2 to mem[rs1+imm]"),
    doc("F", "fadd.s", "frd, frs1, frs2", "frd = frs1 + frs2 (single precision)"),
    doc("F", "fsub.s", "frd, frs1, frs2", "frd = frs1 - frs2"),
    doc("F", "fmul.s", "frd, frs1, frs2", "frd = frs1 * frs2"),
    doc("F", "fdiv.s", "frd, frs1, frs2", "frd = frs1 / frs2"),
    doc("F", "fsqrt.s", "frd, frs1", "frd = sqrt(frs1)"),
    doc("F", "fmin.s", "frd, frs1, frs2", "frd = min(frs1, frs2) (IEEE 754)"),
    doc("F", "fmax.s", "frd, frs1, frs2", "frd = max(frs1, frs2) (IEEE 754)"),
    doc("F", "fmadd.s", "frd, frs1, frs2, frs3", "frd = frs1*frs2 + frs3 (fused)"),
    doc("F", "fmsub.s", "frd, frs1, frs2, frs3", "frd = frs1*frs2 - frs3 (fused)"),
    doc("F", "fnmadd.s", "frd, frs1, frs2, frs3", "frd = -(frs1*frs2) - frs3 (fused)"),
    doc("F", "fnmsub.s", "frd, frs1, frs2, frs3", "frd = -(frs1*frs2) + frs3 (fused)"),
    doc("F", "fsgnj.s", "frd, frs1, frs2", "frd = |frs1| with sign of frs2"),
    doc("F", "fsgnjn.s", "frd, frs1, frs2", "frd = |frs1| with negated sign of frs2"),
    doc("F", "fsgnjx.s", "frd, frs1, frs2", "frd = |frs1| with XOR of signs"),
    doc("F", "feq.s", "rd, frs1, frs2", "rd = 1 if frs1 == frs2 (ordered) else 0"),
    doc("F", "flt.s", "rd, frs1, frs2", "rd = 1 if frs1 < frs2 (ordered) else 0"),
    doc("F", "fle.s", "rd, frs1, frs2", "rd = 1 if frs1 <= frs2 (ordered) else 0"),
    doc("F", "fclass.s", "rd, frs1", "Classify frs1 → bitmask in rd (see ISA)"),
    doc("F", "fcvt.w.s", "rd, frs1[, rm]", "Convert f32 → i32; rm = rounding mode"),
    doc("F", "fcvt.wu.s", "rd, frs1[, rm]", "Convert f32 → u32; rm = rounding mode"),
    doc("F", "fcvt.s.w", "frd, rs1", "Convert i32 → f32"),
    doc("F", "fcvt.s.wu", "frd, rs1", "Convert u32 → f32"),
    doc("F", "fmv.x.w", "rd, frs1", "Copy float bits → int register (no conversion)"),
    doc("F", "fmv.w.x", "frd, rs1", "Copy int bits → float register (no conversion)"),
    expands("F", "fmv.s", "frd, frs", "Copy float register", "fsgnj.s frd, frs, frs"),
    expands("F", "fneg.s", "frd, frs", "Negate: frd = -frs", "fsgnjn.s frd, frs, frs"),
    expands("F", "fabs.s", "frd, frs", "Absolute value: frd = |frs|", "fsgnjx.s frd, frs, frs"),
    doc("Dir", ".data", "", "Switch to initialized data section"),
    doc("Dir", ".text", "", "Switch to code section"),
    doc("Dir", ".bss", "", "Switch to BSS (zero-initialized) section"),
    doc("Dir", ".section", "name", "Switch to named section (.text or .data)"),
    doc("Dir", ".byte", "val[,...]", "Emit 1-byte integer value(s)"),
    doc("Dir", ".half", "val[,...]", "Emit 2-byte value(s) little-endian"),
    doc("Dir", ".word", "val[,...]", "Emit 4-byte value(s) little-endian"),
    doc("Dir", ".dword", "val[,...]", "Emit 8-byte value(s) little-endian"),
    doc("Dir", ".float", "val[,...]", "Emit IEEE 754 f32 value(s) (4 bytes each)"),
    doc("Dir", ".ascii", "\"str\"", "Emit string bytes (no NUL terminator)"),
    doc("Dir", ".asciz", "\"str\"", "Emit string bytes + NUL terminator"),
    doc("Dir", ".string", "\"str\"", "Alias of .asciz"),
    doc("Dir", ".space", "n", "Reserve n zero bytes"),
    doc("Dir", ".align", "n", "Align PC to 2^n byte boundary"),
    doc("Dir", ".globl", "sym", "Mark symbol as global / exported"),
    doc("Dir", ".equ", "sym, val", "Define symbolic constant (equate)"),
];
