#ifndef RAVEN_VERSION_H
#define RAVEN_VERSION_H

#define RAVEN_API_VERSION_MAJOR 1
#define RAVEN_API_VERSION_MINOR 0
#define RAVEN_API_VERSION       ((RAVEN_API_VERSION_MAJOR * 100) + RAVEN_API_VERSION_MINOR)
#define RAVEN_API_AT_LEAST(maj, min) (RAVEN_API_VERSION >= ((maj) * 100 + (min)))

#endif
