use super::common::{blank, h1, h2, kv, mono, note, raw};
use crate::ui::app::DocsLang;
use ratatui::prelude::*;

pub(crate) fn memory_map_lines(lang: DocsLang) -> Vec<Line<'static>> {
    match lang {
        DocsLang::En => memory_map_lines_en(),
        DocsLang::PtBr => memory_map_lines_ptbr(),
    }
}

fn memory_map_lines_en() -> Vec<Line<'static>> {
    vec![
        h1("RAVEN — Memory Map"),
        blank(),
        note(
            "Default RAM = 16 MB · addresses 0x00000000 .. RAM_SIZE-1 · no MMU, no virtual memory",
        ),
        note("RAM size is configurable in the Config tab (accepts e.g. 16mb, 8192kb, 4096)."),
        blank(),
        h2("Layout"),
        blank(),
        mono("  0x00000000  ┌─────────────────────┐"),
        mono(
            "              │  .text  (code)       │  ← instructions start at base_pc (default 0x0)",
        ),
        mono("              ├─────────────────────┤"),
        mono(
            "  0x00001000  │  .data              │  ← initialized data  (data_base = base_pc + 0x1000)",
        ),
        mono("              │  .bss               │  ← zero-initialized; grows up after .data"),
        mono("              ├ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┤"),
        mono(
            "              │   (free space)       │  ← no allocator; read/write freely with lw/sw",
        ),
        mono("              ├ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┤"),
        mono(
            "  RAM_SIZE-1  │  stack  (grows ↓)   │  ← sp = RAM_SIZE (one past end); push: sp-=4, sw rs,0(sp)",
        ),
        mono("              └─────────────────────┘"),
        blank(),
        h2("Sections"),
        blank(),
        kv(".text", "Assembled instructions, loaded at base_pc."),
        kv(
            ".data",
            "Initialized bytes (.byte/.half/.word/.float/.ascii/.asciz).",
        ),
        kv(
            ".bss",
            "Zero-initialized reservation (.space N). No bytes in binary.",
        ),
        blank(),
        h2("Key addresses"),
        blank(),
        kv(
            "base_pc",
            "Start of .text. Configurable; default 0x00000000.",
        ),
        kv("data_base", "Start of .data / .bss = base_pc + 0x1000."),
        kv(
            "sp (initial)",
            "RAM_SIZE — one past end of RAM (RISC-V ABI). First push writes to RAM_SIZE-4.",
        ),
        blank(),
        h2("Free space — no heap allocator"),
        blank(),
        raw("  The region between bss_end and the stack is ordinary RAM with no"),
        raw("  management. You can use it directly with sw/lw if you know the address."),
        raw("  There is no malloc/free — RAVEN has a flat address space"),
        raw("  with no pagination or memory protection."),
        blank(),
        note("Tip: use .bss labels to reserve named buffers without wasting binary space."),
        blank(),
        h2("Example — using free space manually"),
        blank(),
        mono("  .bss"),
        mono("  buf: .space 64      ; reserve 64 bytes (address known at assemble time)"),
        mono("  .text"),
        mono("      la   t0, buf    ; t0 = &buf"),
        mono("      li   t1, 42"),
        mono("      sw   t1, 0(t0)  ; store 42 at buf[0]"),
        mono("      lw   t2, 0(t0)  ; load back → t2 = 42"),
        blank(),
        h2("Manual heap — bump allocator"),
        blank(),
        raw("  To allocate dynamically at runtime, store a heap pointer in .data and"),
        raw("  advance it on each allocation. The heap grows upward; the stack grows"),
        raw("  downward — they will collide if combined use exceeds free space."),
        blank(),
        mono("  .data"),
        mono("  heap_ptr: .word 0x00004000   ; initial heap base (above .bss)"),
        blank(),
        mono("  ; alloc(a1 = size) → a0 = pointer to allocated block"),
        mono("  alloc:"),
        mono("      la   t0, heap_ptr"),
        mono("      lw   a0, 0(t0)      ; a0 = current heap_ptr (return value)"),
        mono("      add  t1, a0, a1     ; t1 = heap_ptr + size"),
        mono("      sw   t1, 0(t0)      ; heap_ptr += size"),
        mono("      ret"),
        blank(),
        note("There is no free() — allocations are permanent for the lifetime of the program."),
        blank(),
        h2("Keyboard Shortcuts — Run tab"),
        blank(),
        kv("Ctrl+g", "Open label/address search in Instruction Memory."),
        kv(
            "",
            "Type a label name or 0x… address; Enter = next match; Esc = close.",
        ),
        kv("s", "Step one instruction on the selected hart."),
        kv("r / p", "Run continuously / pause execution."),
        kv("R", "Restart simulation from the beginning."),
        kv("F9", "Toggle breakpoint at the hovered instruction or current PC."),
        blank(),
        h2("Keyboard Shortcuts — Config tab"),
        blank(),
        kv(
            "Mem Size",
            "Accepts plain KB number, or suffix: 16mb / 8192kb.",
        ),
        kv("", "Value is snapped to the nearest power of two."),
        kv("Enter", "Open edit mode on the selected field."),
        kv("↑ / ↓", "Navigate between fields."),
        kv("Ctrl+e / Ctrl+l", "Export / import the full Config tab as .rcfg."),
    ]
}

fn memory_map_lines_ptbr() -> Vec<Line<'static>> {
    vec![
        h1("RAVEN — Mapa de Memória"),
        blank(),
        note(
            "RAM padrão = 16 MB · endereços 0x00000000 .. RAM_SIZE-1 · sem MMU, sem memória virtual",
        ),
        note("Tamanho configurável na aba Config (aceita ex.: 16mb, 8192kb, 4096)."),
        blank(),
        h2("Layout"),
        blank(),
        mono("  0x00000000  ┌─────────────────────┐"),
        mono(
            "              │  .text  (código)     │  ← instruções começam em base_pc (padrão 0x0)",
        ),
        mono("              ├─────────────────────┤"),
        mono(
            "  0x00001000  │  .data              │  ← dados inicializados  (data_base = base_pc + 0x1000)",
        ),
        mono("              │  .bss               │  ← inicializada com zeros; cresce após .data"),
        mono("              ├ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┤"),
        mono(
            "              │   (espaço livre)     │  ← sem alocador; leitura/escrita livre com lw/sw",
        ),
        mono("              ├ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┤"),
        mono(
            "  RAM_SIZE-1  │  pilha  (cresce ↓)  │  ← sp = RAM_SIZE (um além do fim); push: sp-=4, sw rs,0(sp)",
        ),
        mono("              └─────────────────────┘"),
        blank(),
        h2("Seções"),
        blank(),
        kv(".text", "Instruções montadas, carregadas em base_pc."),
        kv(
            ".data",
            "Bytes inicializados (.byte/.half/.word/.float/.ascii/.asciz).",
        ),
        kv(
            ".bss",
            "Reserva zerada (.space N). Não ocupa espaço no binário.",
        ),
        blank(),
        h2("Endereços importantes"),
        blank(),
        kv(
            "base_pc",
            "Início do .text. Configurável; padrão 0x00000000.",
        ),
        kv("data_base", "Início do .data / .bss = base_pc + 0x1000."),
        kv(
            "sp (inicial)",
            "RAM_SIZE — um além do fim da RAM (ABI RISC-V). Primeiro push escreve em RAM_SIZE-4.",
        ),
        blank(),
        h2("Espaço livre — sem alocador de heap"),
        blank(),
        raw("  A região entre o fim do .bss e a pilha é RAM comum, sem gerenciamento."),
        raw("  Você pode usá-la diretamente com sw/lw se souber o endereço."),
        raw("  Não existe malloc/free — o RAVEN tem um espaço de endereçamento"),
        raw("  plano e sem paginação nem proteção de memória."),
        blank(),
        note(
            "Dica: use labels no .bss para reservar buffers nomeados sem desperdiçar espaço no binário.",
        ),
        blank(),
        h2("Exemplo — usando o espaço livre manualmente"),
        blank(),
        mono("  .bss"),
        mono("  buf: .space 64      ; reserva 64 bytes (endereço conhecido na montagem)"),
        mono("  .text"),
        mono("      la   t0, buf    ; t0 = &buf"),
        mono("      li   t1, 42"),
        mono("      sw   t1, 0(t0)  ; armazena 42 em buf[0]"),
        mono("      lw   t2, 0(t0)  ; lê de volta → t2 = 42"),
        blank(),
        h2("Heap manual — alocador bump"),
        blank(),
        raw("  Para alocar dinamicamente em tempo de execução, armazene um ponteiro de"),
        raw("  heap no .data e avance-o a cada alocação. O heap cresce para cima; a"),
        raw("  pilha cresce para baixo — colidem se o uso combinado exceder o espaço livre."),
        blank(),
        mono("  .data"),
        mono("  heap_ptr: .word 0x00004000   ; base inicial do heap (acima do .bss)"),
        blank(),
        mono("  ; alloc(a1 = tamanho) → a0 = ponteiro para o bloco alocado"),
        mono("  alloc:"),
        mono("      la   t0, heap_ptr"),
        mono("      lw   a0, 0(t0)      ; a0 = heap_ptr atual (valor de retorno)"),
        mono("      add  t1, a0, a1     ; t1 = heap_ptr + tamanho"),
        mono("      sw   t1, 0(t0)      ; heap_ptr += tamanho"),
        mono("      ret"),
        blank(),
        note("Não existe free() — as alocações são permanentes durante a execução do programa."),
        blank(),
        h2("Atalhos de Teclado — aba Run"),
        blank(),
        kv(
            "Ctrl+g",
            "Abre pesquisa de label/endereço na Memória de Instruções.",
        ),
        kv(
            "",
            "Digite o nome da label ou 0x…; Enter = próximo; Esc = fechar.",
        ),
        kv("s", "Avança uma instrução no hart selecionado."),
        kv("r / p", "Inicia execução contínua / pausa a execução."),
        kv("R", "Reinicia a simulação do início."),
        kv("F9", "Alterna breakpoint na instrução sob o cursor ou no PC atual."),
        blank(),
        h2("Atalhos de Teclado — aba Config"),
        blank(),
        kv("Mem Size", "Aceita número em KB, ou sufixo: 16mb / 8192kb."),
        kv(
            "",
            "Valor arredondado para a potência de dois mais próxima.",
        ),
        kv("Enter", "Abre edição no campo selecionado."),
        kv("↑ / ↓", "Navega entre os campos."),
        kv("Ctrl+e / Ctrl+l", "Exporta / importa a aba Config completa como .rcfg."),
    ]
}
